apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dpadeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment            # we can change if it is ReplicationController or ReplicaSet
    name: dpadeploymen          ## we can change if it is ReplicationController or ReplicaSet name should be given
  minReplicas: 2        
  maxReplicas: 4
  metrics:
  - type: Resource      # we can scale based upon cpu or memory depending upon requirement. if we want we can mention both cpu and memory like this deployment-file
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 40
