apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfspv
  namespace: test-ns
spec:
  capacity: 
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.31.2.46    #nfs server IP
    path: /mnt/nfs_share

