apiVersion: v1
kind: Pod                 #resource name should start with capital letter
metadata:
  name: mavenwebapppod
  labels: 
    app: mavenwebapp
  namespace: test-ns
spec:
  containers:
  - name: mavenwebappcontainer
    image: dockerhandson/maven-web-application:1
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc    #we can give any meaningful name
  namespace: test-ns
spec:              #spec will be changed according to resource type
  type: NodePort
  selector: 
    app: mavenwebapp  #< pod labels key>: <pod lable value> #labels should match
  ports:
  - port: 80
    targetPort: 8080
