apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: shahrukh338/java-web-app:31
    ports:
    - containerPort: 8080
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
spec:
  type: NodePort
  selector: 
    app: javawebapp
  ports:
  - port: 8080
    targetPort: 8080
    name: tomcat
  - port: 80
    targetPort: 80
    name: nginx
