apiVersion: v1
kind: ReplicationController
metadata:       # this metadata is for ReplicationController
  name: mavenwebapprc
  namespace: test-ns
# labels:       #NOT Mandatory to define labels
 
spec:           # this is ReplicationController specification
  replicas: 3   # default replica is 1
  selector:    # Not mandatory if we want we can give
    app: mavenwebapp
  template:     # POD template
    metadata:   # this metadata for POD 
      name: mavenwebapppod #pod name
      labels:   #pod labels
        app: mavenwebapp
    spec:         #this is POD specificatio  
      containers:
      - name: mavenwebappcontainer
        image: shahrukh338/java-web-app:31
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080
