apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodejsrs
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template: 
    metadata:
      name: nodeapppod
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeappcontainer
        image: shahrukh338/java-web-app:31
        ports: 
        - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsappsvc
  namespace: test-ns
spec: 
  type: NodePort
  selector: 
    app: nodeapp
  ports:
  - port: 80
    targetPort: 9981
